language: "en"
pipeline:
  - name: WhitespaceTokenizer
    case_sensitive: False
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "bert-base-uncased"
    cache_dir: lfs
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
#  - name: DucklingEntityExtractor
#    url: "http://duckling:8000"
#    dimensions: []  # Add dimensions if the DDD has built-in the sorts integer or datetime e.g. ["number", "time"]
  - name: EntitySynonymMapper

version: "2.0"

nlu:
- intent: action::baked_mushroom_risotto_recipe_action
  examples: |
    - make a risotto
    - I want to make a risotto
    - a risotto
    - Can you show me, how to make a risotto

- intent: action::fries_recipe_action
  examples: |
    - make fries
    - I want to make fries
    - french fries
    - chips
    - Can you show me, how to make fries
    - I would like to do fries
    - baked potatoes

- intent: action::omelette_recipe_action
  examples: |
    - prepare a French omelette
    - I want to prepare a French omelette
    - I would like to do a French omelette
    - a French omelette
    - French omelette
    - Give me the instructions for a French omelette
    - an omelette

- intent: question::amount_ingredient
  examples: |
    - How much [black pepper]{"entity": "sort.ingredient", "value": "individual.black_pepper"} should I use
    - How much [garlic]{"entity": "sort.ingredient", "value": "individual.garlic"} should I use
    - How much [mixed mushrooms]{"entity": "sort.ingredient", "value": "individual.mixed_mushrooms"} should I use
    - How much [olive oil]{"entity": "sort.ingredient", "value": "individual.olive_oil"} should I use
    - How much [omelette]{"entity": "sort.ingredient", "value": "individual.omelette"} should I use
    - How much [potato]{"entity": "sort.ingredient", "value": "individual.potato"} should I use
    - How much [rosemary]{"entity": "sort.ingredient", "value": "individual.rosemary"} should I use
    - How much [salt]{"entity": "sort.ingredient", "value": "individual.salt"} should I use
    - How much [stock]{"entity": "sort.ingredient", "value": "individual.stock"} should I use
    - How much [wine]{"entity": "sort.ingredient", "value": "individual.wine"} should I use
    - How many [black pepper]{"entity": "sort.ingredient", "value": "individual.black_pepper"}
    - How many [egg mixture]{"entity": "sort.ingredient", "value": "individual.egg_mixture"}
    - How many [egg]{"entity": "sort.ingredient", "value": "individual.egg"}
    - How many [garlic]{"entity": "sort.ingredient", "value": "individual.garlic"}
    - How many [oil]{"entity": "sort.ingredient", "value": "individual.oil"}
    - How many [olive oil]{"entity": "sort.ingredient", "value": "individual.olive_oil"}
    - How many [omelette]{"entity": "sort.ingredient", "value": "individual.omelette"}
    - How many [onion]{"entity": "sort.ingredient", "value": "individual.onion"}
    - How many [potato]{"entity": "sort.ingredient", "value": "individual.potato"}
    - How many [wine]{"entity": "sort.ingredient", "value": "individual.wine"}
    - How much
    - A lot
    - What is the amount

- intent: answer
  examples: |
    - [single](sort.string)
    - [double word](sort.string)
    - [three in one](sort.string)
    - [hey make it four](sort.string)
    - [the more the merrier five](sort.string)
    - [calm down and count to six](sort.string)
    - [bring them through to the jolly seven](sort.string)
    - [noone counts toes like an eight toed guy](sort.string)
    - [it matters to make sense for nine of us](sort.string)
    - [would you bring ten or none to a desert island](sort.string)
    - [omelette recipe]{"entity": "sort.recipe", "value": "individual.omelette_recipe"}
    - [fries recipe]{"entity": "sort.recipe", "value": "individual.fries_recipe"}
    - [baked mushroom risotto recipe]{"entity": "sort.recipe", "value": "individual.baked_mushroom_risotto_recipe"}
    - [omelette recipe_step_0]{"entity": "sort.step", "value": "individual.omelette_recipe_step_0"}
    - [omelette recipe_step_1]{"entity": "sort.step", "value": "individual.omelette_recipe_step_1"}
    - [omelette recipe_step_2]{"entity": "sort.step", "value": "individual.omelette_recipe_step_2"}
    - [omelette recipe_step_3]{"entity": "sort.step", "value": "individual.omelette_recipe_step_3"}
    - [omelette recipe_step_4]{"entity": "sort.step", "value": "individual.omelette_recipe_step_4"}
    - [fries recipe_step_0]{"entity": "sort.step", "value": "individual.fries_recipe_step_0"}
    - [fries recipe_step_1]{"entity": "sort.step", "value": "individual.fries_recipe_step_1"}
    - [fries recipe_step_2]{"entity": "sort.step", "value": "individual.fries_recipe_step_2"}
    - [fries recipe_step_3]{"entity": "sort.step", "value": "individual.fries_recipe_step_3"}
    - [fries recipe_step_4]{"entity": "sort.step", "value": "individual.fries_recipe_step_4"}
    - [baked mushroom risotto recipe_step_0]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_0"}
    - [baked mushroom risotto recipe_step_1]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_1"}
    - [baked mushroom risotto recipe_step_2]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_2"}
    - [baked mushroom risotto recipe_step_3]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_3"}
    - [baked mushroom risotto recipe_step_4]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_4"}
    - [baked mushroom risotto recipe_step_5]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_5"}
    - [baked mushroom risotto recipe_step_6]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_6"}
    - [baked mushroom risotto recipe_step_7]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_7"}
    - [baked mushroom risotto recipe_step_8]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_8"}
    - [baked mushroom risotto recipe_step_9]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_9"}
    - [baked mushroom risotto recipe_step_10]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_10"}
    - [baked mushroom risotto recipe_step_11]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_11"}
    - [baked mushroom risotto recipe_step_12]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_12"}
    - [baked mushroom risotto recipe_step_13]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_13"}
    - [baked mushroom risotto recipe_step_14]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_14"}
    - [baked mushroom risotto recipe_step_15]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_15"}
    - [baked mushroom risotto recipe_step_16]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_16"}
    - [wine]{"entity": "sort.ingredient", "value": "individual.wine"}
    - [salt]{"entity": "sort.ingredient", "value": "individual.salt"}
    - [egg]{"entity": "sort.ingredient", "value": "individual.egg"}
    - [stock]{"entity": "sort.ingredient", "value": "individual.stock"}
    - [black pepper]{"entity": "sort.ingredient", "value": "individual.black_pepper"}
    - [mixed mushrooms]{"entity": "sort.ingredient", "value": "individual.mixed_mushrooms"}
    - [butter]{"entity": "sort.ingredient", "value": "individual.butter"}
    - [oil]{"entity": "sort.ingredient", "value": "individual.oil"}
    - [olive oil]{"entity": "sort.ingredient", "value": "individual.olive_oil"}
    - [omelette]{"entity": "sort.ingredient", "value": "individual.omelette"}
    - [garlic]{"entity": "sort.ingredient", "value": "individual.garlic"}
    - [risotto]{"entity": "sort.ingredient", "value": "individual.risotto"}
    - [rosemary]{"entity": "sort.ingredient", "value": "individual.rosemary"}
    - [onion]{"entity": "sort.ingredient", "value": "individual.onion"}
    - [potato]{"entity": "sort.ingredient", "value": "individual.potato"}
    - [parmesan]{"entity": "sort.ingredient", "value": "individual.parmesan"}
    - [risotto rice]{"entity": "sort.ingredient", "value": "individual.risotto_rice"}
    - [egg mixture]{"entity": "sort.ingredient", "value": "individual.egg_mixture"}
    - [pan]{"entity": "sort.object", "value": "individual.pan"}
    - [heat]{"entity": "sort.object", "value": "individual.heat"}
    - [bowl]{"entity": "sort.object", "value": "individual.bowl"}
    - [baking sheet]{"entity": "sort.object", "value": "individual.baking_sheet"}
    - [oven]{"entity": "sort.object", "value": "individual.oven"}
    - [lid]{"entity": "sort.object", "value": "individual.lid"}
    - [plate]{"entity": "sort.object", "value": "individual.plate"}
    - [mixing bowl]{"entity": "sort.object", "value": "individual.mixing_bowl"}
    - [oven proof lidded dish]{"entity": "sort.object", "value": "individual.oven_proof_lidded_dish"}
    - yes [single](sort.string)
    - yes [omelette recipe]{"entity": "sort.recipe", "value": "individual.omelette_recipe"}
    - yes [fries recipe_step_2]{"entity": "sort.step", "value": "individual.fries_recipe_step_2"}
    - yes [baked mushroom risotto recipe_step_7]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_7"}
    - yes [wine]{"entity": "sort.ingredient", "value": "individual.wine"}
    - yes [garlic]{"entity": "sort.ingredient", "value": "individual.garlic"}
    - yes [bowl]{"entity": "sort.object", "value": "individual.bowl"}
    - no [double word](sort.string)
    - no [fries recipe]{"entity": "sort.recipe", "value": "individual.fries_recipe"}
    - no [fries recipe_step_3]{"entity": "sort.step", "value": "individual.fries_recipe_step_3"}
    - no [baked mushroom risotto recipe_step_8]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_8"}
    - no [salt]{"entity": "sort.ingredient", "value": "individual.salt"}
    - no [risotto]{"entity": "sort.ingredient", "value": "individual.risotto"}
    - no [baking sheet]{"entity": "sort.object", "value": "individual.baking_sheet"}

- intent: answer_negation
  examples: |
    - not [omelette recipe]{"entity": "sort.recipe", "value": "individual.omelette_recipe"}
    - not [fries recipe]{"entity": "sort.recipe", "value": "individual.fries_recipe"}
    - not [baked mushroom risotto recipe]{"entity": "sort.recipe", "value": "individual.baked_mushroom_risotto_recipe"}
    - not [omelette recipe_step_0]{"entity": "sort.step", "value": "individual.omelette_recipe_step_0"}
    - not [omelette recipe_step_1]{"entity": "sort.step", "value": "individual.omelette_recipe_step_1"}
    - not [omelette recipe_step_2]{"entity": "sort.step", "value": "individual.omelette_recipe_step_2"}
    - not [omelette recipe_step_3]{"entity": "sort.step", "value": "individual.omelette_recipe_step_3"}
    - not [omelette recipe_step_4]{"entity": "sort.step", "value": "individual.omelette_recipe_step_4"}
    - not [fries recipe_step_0]{"entity": "sort.step", "value": "individual.fries_recipe_step_0"}
    - not [fries recipe_step_1]{"entity": "sort.step", "value": "individual.fries_recipe_step_1"}
    - not [fries recipe_step_2]{"entity": "sort.step", "value": "individual.fries_recipe_step_2"}
    - not [fries recipe_step_3]{"entity": "sort.step", "value": "individual.fries_recipe_step_3"}
    - not [fries recipe_step_4]{"entity": "sort.step", "value": "individual.fries_recipe_step_4"}
    - not [baked mushroom risotto recipe_step_0]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_0"}
    - not [baked mushroom risotto recipe_step_1]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_1"}
    - not [baked mushroom risotto recipe_step_2]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_2"}
    - not [baked mushroom risotto recipe_step_3]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_3"}
    - not [baked mushroom risotto recipe_step_4]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_4"}
    - not [baked mushroom risotto recipe_step_5]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_5"}
    - not [baked mushroom risotto recipe_step_6]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_6"}
    - not [baked mushroom risotto recipe_step_7]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_7"}
    - not [baked mushroom risotto recipe_step_8]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_8"}
    - not [baked mushroom risotto recipe_step_9]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_9"}
    - not [baked mushroom risotto recipe_step_10]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_10"}
    - not [baked mushroom risotto recipe_step_11]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_11"}
    - not [baked mushroom risotto recipe_step_12]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_12"}
    - not [baked mushroom risotto recipe_step_13]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_13"}
    - not [baked mushroom risotto recipe_step_14]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_14"}
    - not [baked mushroom risotto recipe_step_15]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_15"}
    - not [baked mushroom risotto recipe_step_16]{"entity": "sort.step", "value": "individual.baked_mushroom_risotto_recipe_step_16"}
    - not [wine]{"entity": "sort.ingredient", "value": "individual.wine"}
    - not [salt]{"entity": "sort.ingredient", "value": "individual.salt"}
    - not [egg]{"entity": "sort.ingredient", "value": "individual.egg"}
    - not [stock]{"entity": "sort.ingredient", "value": "individual.stock"}
    - not [black pepper]{"entity": "sort.ingredient", "value": "individual.black_pepper"}
    - not [mixed mushrooms]{"entity": "sort.ingredient", "value": "individual.mixed_mushrooms"}
    - not [butter]{"entity": "sort.ingredient", "value": "individual.butter"}
    - not [oil]{"entity": "sort.ingredient", "value": "individual.oil"}
    - not [olive oil]{"entity": "sort.ingredient", "value": "individual.olive_oil"}
    - not [omelette]{"entity": "sort.ingredient", "value": "individual.omelette"}
    - not [garlic]{"entity": "sort.ingredient", "value": "individual.garlic"}
    - not [risotto]{"entity": "sort.ingredient", "value": "individual.risotto"}
    - not [rosemary]{"entity": "sort.ingredient", "value": "individual.rosemary"}
    - not [onion]{"entity": "sort.ingredient", "value": "individual.onion"}
    - not [potato]{"entity": "sort.ingredient", "value": "individual.potato"}
    - not [parmesan]{"entity": "sort.ingredient", "value": "individual.parmesan"}
    - not [risotto rice]{"entity": "sort.ingredient", "value": "individual.risotto_rice"}
    - not [egg mixture]{"entity": "sort.ingredient", "value": "individual.egg_mixture"}
    - not [pan]{"entity": "sort.object", "value": "individual.pan"}
    - not [heat]{"entity": "sort.object", "value": "individual.heat"}
    - not [bowl]{"entity": "sort.object", "value": "individual.bowl"}
    - not [baking sheet]{"entity": "sort.object", "value": "individual.baking_sheet"}
    - not [oven]{"entity": "sort.object", "value": "individual.oven"}
    - not [lid]{"entity": "sort.object", "value": "individual.lid"}
    - not [plate]{"entity": "sort.object", "value": "individual.plate"}
    - not [mixing bowl]{"entity": "sort.object", "value": "individual.mixing_bowl"}
    - not [oven proof lidded dish]{"entity": "sort.object", "value": "individual.oven_proof_lidded_dish"}

- intent: NEGATIVE
  examples: |
    - aboard
    - about
    - above
    - across
    - after
    - against
    - along
    - among
    - as
    - at
    - on
    - atop
    - before
    - behind
    - below
    - beneath
    - beside
    - between
    - beyond
    - but
    - by
    - come
    - down
    - during
    - except
    - for
    - from
    - in
    - inside
    - into
    - less
    - like
    - near
    - of
    - off
    - on
    - onto
    - opposite
    - out
    - outside
    - over
    - past
    - save
    - short
    - since
    - than
    - then
    - through
    - throughout
    - to
    - toward
    - under
    - underneath
    - unlike
    - until
    - up
    - upon
    - with
    - within
    - without
    - worth
    - is
    - it
    - the
    - a
    - am
    - are
    - them
    - this
    - that
    - I
    - you
    - he
    - she
    - they
    - them
    - his
    - her
    - my
    - mine
    - their
    - your
    - us
    - our
    - how
    - how's
    - how is
    - how's the
    - how is the
    - when
    - when's
    - when is
    - when is the
    - when's the
    - what
    - what is
    - what's
    - what's the
    - what is the
    - why
    - why is
    - why's
    - why is the
    - why's the
    - do
    - make
    - tell
    - start
    - stop
    - enable
    - disable
    - raise
    - lower
    - decrease
    - increase
    - act
    - determine
    - say
    - ask
    - go
    - shoot
    - wait
    - hang on
    - ok
    - show
    - help

- intent: answer:yes
  examples: |
    - yes
    - yeah
    - yep
    - sure
    - ok
    - of course
    - very well
    - fine
    - right
    - excellent
    - okay
    - perfect
    - I think so

- intent: answer:no
  examples: |
    - no
    - nope
    - no thanks
    - no thank you
    - negative
    - don't want to
    - don't
    - do not
    - please don't

- intent: request:top
  examples: |
    - forget it
    - never mind
    - get me out of here
    - start over
    - beginning
    - never mind that
    - restart

- intent: request:up
  examples: |
    - go back
    - back
    - previous
    - back to the previous
    - go to the previous
    - go back to the previous one

- intent: request:how
  examples: |
    - how do I do that
    - how
    - can you tell me how to do that
    - I don't know how should I do that
    - how can I do that

- intent: report:done
  examples: |
    - I'm done
    - done
    - ready
    - it's ready
    - I'm ready
    - completed
    - check
    - I have finished
    - finished
    - done and done
    - it's done now
    - okay next
    - next
    - next instruction

- intent: icm:per*neg
  examples: |
    - repeat
    - repeat it
    - repeat that
    - pardon
    - sorry
    - can you repeat that
    - excuse me
    - what was that
    - what did you say
    - come again

- intent: icm:acc*neg:issue
  examples: |
    - I don't know
    - I don't know that
    - it doesn't matter

- intent: thanks
  examples: |
    - thank you
    - thank you very much
    - thanks
    - big thanks
    - thanks a lot

- intent: greet
  examples: |
    - hello
    - hi
    - good day
    - what's up
    - good evening
    - good morning
    - hey


